# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citypincode',
            fields=[
                ('pincode', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Couriercompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(choices=[('Delhivery', 'Delhivery'), ('Fedex', 'Fedex'), ('Dotzot', 'Dotzot'), ('DTDC', 'DTDC'), ('Indiapost', 'Indiapost')], default='Delhivery', max_length=200)),
                ('limit', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('preference', models.IntegerField(choices=[(1, 'Preference 1'), (2, 'Preference 2'), (3, 'Preference 3'), (4, 'Preference 4'), (5, 'Preference 5')], default=1)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriercompanies', to='couriercompany.Citypincode')),
            ],
        ),
    ]
